version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: marcblend/docker-circleci
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run: |
          npm install -g lerna
          yarn install
          lerna run build
          lerna run test
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
